### ISSUE TITLE
Do you welcome contributions?

### ISSUE THREAD

**Issue by piq9117** [unclechu/purescript-for-haskellers#1]
Thanks for this! I am currently learning haskell and found this helpful when I'm trying to implement what I've learned in haskell into purescript. I was wondering if I could help with this guide whenever I see if there are changes that need to be made?

**Comment by unclechu** [comment]
@piq9117 Good to know it had helped someone. Yes, PRs are welcomed, why not, just keep in mind that this only one yet instruction supposed to be expressive but short and simple. If you have something big to add then just create another document you could refer to from main one.

**Comment by piq9117** [comment]
Awesome! thanks.
